import { AnalyticsPermissions } from 'shared/analytics-permissions/analytics-permissions';

export const AnalyticsPermissionsRules: {
  customPermissionKeyToNameMapping: { [key: number]: string },
  requiredPermissionMapping: { [key: number]: AnalyticsPermissions },
  linkedPermissionMapping: { [key: number]: AnalyticsPermissions }
} = {
  customPermissionKeyToNameMapping: {
    [AnalyticsPermissions.CUEPOINT_MANAGE]: 'cuePoint.MANAGE',
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_DELETE]: 'dropFolder.CONTENT_INGEST_DROP_FOLDER_DELETE',
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_MATCH]: 'dropFolder.CONTENT_INGEST_DROP_FOLDER_MATCH',
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_BASE]: 'dropFolder.CONTENT_INGEST_DROP_FOLDER_BASE'
  },
  requiredPermissionMapping: {
    [AnalyticsPermissions.CONTENT_INGEST_REMOTE_STORAGE]: AnalyticsPermissions.FEATURE_REMOTE_STORAGE_INGEST,
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_MATCH]: AnalyticsPermissions.CONTENT_INGEST_DROP_FOLDER_MATCH,
    [AnalyticsPermissions.LIVE_STREAM_ADD]: AnalyticsPermissions.FEATURE_LIVE_STREAM,
    [AnalyticsPermissions.CONTENT_MANAGE_CUSTOM_DATA]: AnalyticsPermissions.METADATA_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CONTENT_MANAGE_ENTRY_USERS]: AnalyticsPermissions.FEATURE_END_USER_MANAGE,
    [AnalyticsPermissions.CONTENT_INGEST_INTO_READY]: AnalyticsPermissions.FEATURE_ENTRY_REPLACEMENT,
    [AnalyticsPermissions.CONTENT_INGEST_REPLACE]: AnalyticsPermissions.FEATURE_ENTRY_REPLACEMENT_APPROVAL,
    [AnalyticsPermissions.CONTENT_INGEST_CLIP_MEDIA]: AnalyticsPermissions.FEATURE_CLIP_MEDIA,
    [AnalyticsPermissions.CONTENT_MANAGE_CATEGORY_USERS]: AnalyticsPermissions.FEATURE_ENTITLEMENT,
    [AnalyticsPermissions.LIVE_STREAM_UPDATE]: AnalyticsPermissions.FEATURE_LIVE_STREAM,
    [AnalyticsPermissions.CUEPOINT_MANAGE]: AnalyticsPermissions.ADCUEPOINT_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CAPTION_MODIFY]: AnalyticsPermissions.CAPTION_PLUGIN_PERMISSION,
    [AnalyticsPermissions.ATTACHMENT_MODIFY]: AnalyticsPermissions.ATTACHMENT_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CONTENT_MODERATE_CUSTOM_DATA]: AnalyticsPermissions.METADATA_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_BASE]: AnalyticsPermissions.CONTENTDISTRIBUTION_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_WHERE]: AnalyticsPermissions.CONTENTDISTRIBUTION_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_SEND]: AnalyticsPermissions.CONTENTDISTRIBUTION_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_REMOVE]: AnalyticsPermissions.CONTENTDISTRIBUTION_PLUGIN_PERMISSION,
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_BASE]: AnalyticsPermissions.DROPFOLDER_PLUGIN_PERMISSION,
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_DELETE]: AnalyticsPermissions.DROPFOLDER_PLUGIN_PERMISSION,
    [AnalyticsPermissions.ADVERTISING_UPDATE_SETTINGS]: AnalyticsPermissions.FEATURE_VAST,
    [AnalyticsPermissions.ANALYTICS_BASE]: AnalyticsPermissions.FEATURE_ANALYTICS_TAB,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_BASE]: AnalyticsPermissions.METADATA_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_ADD]: AnalyticsPermissions.METADATA_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_UPDATE]: AnalyticsPermissions.METADATA_PLUGIN_PERMISSION,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_DELETE]: AnalyticsPermissions.METADATA_PLUGIN_PERMISSION,
    [AnalyticsPermissions.ADMIN_USER_BULK]: AnalyticsPermissions.FEATURE_END_USER_MANAGE
  },
  linkedPermissionMapping: {
    [AnalyticsPermissions.ACCESS_CONTROL_ADD]: AnalyticsPermissions.ACCESS_CONTROL_BASE,
    [AnalyticsPermissions.ACCESS_CONTROL_DELETE]: AnalyticsPermissions.ACCESS_CONTROL_BASE,
    [AnalyticsPermissions.ACCESS_CONTROL_UPDATE]: AnalyticsPermissions.ACCESS_CONTROL_BASE,
    [AnalyticsPermissions.ACCOUNT_UPDATE_SETTINGS]: AnalyticsPermissions.ACCOUNT_BASE,
    [AnalyticsPermissions.ADMIN_ROLE_ADD]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ADMIN_ROLE_DELETE]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ADMIN_ROLE_UPDATE]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ADMIN_USER_ADD]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ADMIN_USER_BULK]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ADMIN_USER_DELETE]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ADMIN_USER_UPDATE]: AnalyticsPermissions.ADMIN_BASE,
    [AnalyticsPermissions.ATTACHMENT_MODIFY]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.BULK_LOG_DELETE]: AnalyticsPermissions.BULK_LOG_BASE,
    [AnalyticsPermissions.BULK_LOG_DOWNLOAD]: AnalyticsPermissions.BULK_LOG_BASE,
    [AnalyticsPermissions.CAPTION_MODIFY]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_BULK_UPLOAD]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_CLIP_MEDIA]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_EXTERNAL_SEARCH]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_INTO_ORPHAN]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_INTO_READY]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_ORPHAN_AUDIO]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_ORPHAN_VIDEO]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_REFERENCE_MODIFY]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_REMOTE_STORAGE]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_REPLACE]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_UPLOAD]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_INGEST_WEBCAM]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_ACCESS_CONTROL]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_ASSIGN_CATEGORIES]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_CATEGORY_USERS]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_CUSTOM_DATA]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_DELETE]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_REMOVE]: AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_SEND]: AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_WHERE]: AnalyticsPermissions.CONTENT_MANAGE_DISTRIBUTION_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_DOWNLOAD]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_EDIT_CATEGORIES]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_EMBED_CODE]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_ENTRY_USERS]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_METADATA]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_RECONVERT]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_SCHEDULE]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MANAGE_THUMBNAIL]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CONTENT_MODERATE_APPROVE_REJECT]: AnalyticsPermissions.CONTENT_MODERATE_BASE,
    [AnalyticsPermissions.CONTENT_MODERATE_CUSTOM_DATA]: AnalyticsPermissions.CONTENT_MODERATE_BASE,
    [AnalyticsPermissions.CONTENT_MODERATE_METADATA]: AnalyticsPermissions.CONTENT_MODERATE_BASE,
    [AnalyticsPermissions.CUEPOINT_MANAGE]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_ADD]: AnalyticsPermissions.CUSTOM_DATA_PROFILE_BASE,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_DELETE]: AnalyticsPermissions.CUSTOM_DATA_PROFILE_BASE,
    [AnalyticsPermissions.CUSTOM_DATA_PROFILE_UPDATE]: AnalyticsPermissions.CUSTOM_DATA_PROFILE_BASE,
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_DELETE]: AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_BASE,
    [AnalyticsPermissions.DROPFOLDER_CONTENT_INGEST_DROP_FOLDER_MATCH]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.INTEGRATION_UPDATE_SETTINGS]: AnalyticsPermissions.INTEGRATION_BASE,
    [AnalyticsPermissions.LIVE_STREAM_ADD]: AnalyticsPermissions.CONTENT_INGEST_BASE,
    [AnalyticsPermissions.LIVE_STREAM_UPDATE]: AnalyticsPermissions.CONTENT_MANAGE_BASE,
    [AnalyticsPermissions.PLAYLIST_ADD]: AnalyticsPermissions.PLAYLIST_BASE,
    [AnalyticsPermissions.PLAYLIST_DELETE]: AnalyticsPermissions.PLAYLIST_BASE,
    [AnalyticsPermissions.PLAYLIST_EMBED_CODE]: AnalyticsPermissions.PLAYLIST_BASE,
    [AnalyticsPermissions.PLAYLIST_UPDATE]: AnalyticsPermissions.PLAYLIST_BASE,
    [AnalyticsPermissions.STUDIO_ADD_UICONF]: AnalyticsPermissions.STUDIO_BASE,
    [AnalyticsPermissions.STUDIO_DELETE_UICONF]: AnalyticsPermissions.STUDIO_BASE,
    [AnalyticsPermissions.STUDIO_SELECT_CONTENT]: AnalyticsPermissions.STUDIO_BASE,
    [AnalyticsPermissions.STUDIO_UPDATE_UICONF]: AnalyticsPermissions.STUDIO_BASE,
    [AnalyticsPermissions.SYNDICATION_ADD]: AnalyticsPermissions.SYNDICATION_BASE,
    [AnalyticsPermissions.SYNDICATION_DELETE]: AnalyticsPermissions.SYNDICATION_BASE,
    [AnalyticsPermissions.SYNDICATION_UPDATE]: AnalyticsPermissions.SYNDICATION_BASE,
    [AnalyticsPermissions.TRANSCODING_ADD]: AnalyticsPermissions.TRANSCODING_BASE,
    [AnalyticsPermissions.TRANSCODING_DELETE]: AnalyticsPermissions.TRANSCODING_BASE,
    [AnalyticsPermissions.TRANSCODING_UPDATE]: AnalyticsPermissions.TRANSCODING_BASE,
  }
};
