name: Trigger Private Repository Workflow

on:
  release:
    types: [created]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          APP_NAME: "kmc-analytics"
          TAG: ${{ github.ref_name }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_TYPE: "public"
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          https://api.github.com/repos/kaltura/ovp-statboy/actions/workflows/deploy-uiconf.yaml/dispatches \
          -d "{\"ref\":\"master\",\"inputs\":{\"app_name\":\"$APP_NAME\",\"tag\":\"$TAG\",\"repo_name\":\"$REPO_NAME\",\"repo_type\":\"$REPO_TYPE\"}}"
